# Generated by Django 4.1.2 on 2023-06-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassengerId', models.CharField(max_length=50)),
                ('Pclass', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=50)),
                ('Sex', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Sibsp', models.IntegerField()),
                ('Parch', models.IntegerField()),
                ('Ticket', models.CharField(max_length=50)),
                ('Fare', models.FloatField()),
                ('Cabin', models.CharField(blank=True, max_length=50, null=True)),
                ('Embarked', models.CharField(max_length=50)),
                ('Survived', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
