# Generated by Django 4.1.2 on 2023-06-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanic',
            name='Embarked',
            field=models.CharField(choices=[('S', 'S'), ('C', 'C'), ('Q', 'Q')], max_length=50),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='Sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50),
        ),
    ]
