# Generated by Django 4.1.2 on 2023-06-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLapi', '0002_alter_titanic_embarked_alter_titanic_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanic',
            name='Pclass',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=0),
        ),
    ]
